[package]
name = "rustls-symcrypt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustls = { git = "https://github.com/rustls/rustls.git" }
symcrypt = "0.1.0"
hex = "0.4.3"
